<?php

use Illuminate\Database\Seeder;
use App\Model\Admin\Menu;
class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menu =array (
            0 =>
                array (
                    'id' => 1,
                    'name' => '文章管理',
                    'pid' => 0,
                    'action' => 'article_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-pencil',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 0,
                ),
            1 =>
                array (
                    'id' => 2,
                    'name' => '商品管理',
                    'pid' => 0,
                    'action' => 'goods_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-shopping-cart',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 10,
                ),
            2 =>
                array (
                    'id' => 3,
                    'name' => '菜单管理',
                    'pid' => 0,
                    'action' => 'menu_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-th-list',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 20,
                ),
            3 =>
                array (
                    'id' => 4,
                    'name' => '用户管理',
                    'pid' => 0,
                    'action' => 'user_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-user',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 30,
                ),
            4 =>
                array (
                    'id' => 5,
                    'name' => '批量维护',
                    'pid' => 0,
                    'action' => 'extension_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-cloud',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 40,
                ),
            5 =>
                array (
                    'id' => 6,
                    'name' => '设置',
                    'pid' => 0,
                    'action' => 'sysconfig_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-wrench',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 1000,
                ),
            6 =>
                array (
                    'id' => 7,
                    'name' => '页面跳转',
                    'pid' => 5,
                    'action' => 'admin_jump',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 1,
                ),
            7 =>
                array (
                    'id' => 8,
                    'name' => '后台首页',
                    'pid' => 5,
                    'action' => 'admin',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 2,
                ),
            8 =>
                array (
                    'id' => 9,
                    'name' => '更新系统参数配置',
                    'pid' => 5,
                    'action' => 'admin_index_upconfig',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 3,
                ),
            9 =>
                array (
                    'id' => 10,
                    'name' => '更新缓存',
                    'pid' => 5,
                    'action' => 'admin_index_upcache',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 4,
                ),
            10 =>
                array (
                    'id' => 11,
                    'name' => '文章列表',
                    'pid' => 1,
                    'action' => 'admin_article',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            11 =>
                array (
                    'id' => 12,
                    'name' => '发布文章',
                    'pid' => 1,
                    'action' => 'admin_article_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            12 =>
                array (
                    'id' => 13,
                    'name' => '发布文章提交',
                    'pid' => 12,
                    'action' => 'admin_article_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            13 =>
                array (
                    'id' => 14,
                    'name' => '文章修改',
                    'pid' => 1,
                    'action' => 'admin_article_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            14 =>
                array (
                    'id' => 15,
                    'name' => '文章修改提交',
                    'pid' => 14,
                    'action' => 'admin_article_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            15 =>
                array (
                    'id' => 16,
                    'name' => '文章删除',
                    'pid' => 1,
                    'action' => 'admin_article_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            16 =>
                array (
                    'id' => 17,
                    'name' => '重复文档检测',
                    'pid' => 1,
                    'action' => 'admin_article_repetarc',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            17 =>
                array (
                    'id' => 18,
                    'name' => '文章推荐',
                    'pid' => 1,
                    'action' => 'admin_article_recommendarc',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            18 =>
                array (
                    'id' => 19,
                    'name' => '文章是否存在',
                    'pid' => 1,
                    'action' => 'admin_article_articleexists',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            19 =>
                array (
                    'id' => 20,
                    'name' => '文章栏目',
                    'pid' => 1,
                    'action' => 'admin_category',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            20 =>
                array (
                    'id' => 21,
                    'name' => '文章栏目添加',
                    'pid' => 20,
                    'action' => 'admin_category_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            21 =>
                array (
                    'id' => 22,
                    'name' => '文章栏目添加提交',
                    'pid' => 21,
                    'action' => 'admin_category_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            22 =>
                array (
                    'id' => 23,
                    'name' => '文章栏目修改',
                    'pid' => 20,
                    'action' => 'admin_category_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            23 =>
                array (
                    'id' => 24,
                    'name' => '文章栏目修改提交',
                    'pid' => 23,
                    'action' => 'admin_category_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            24 =>
                array (
                    'id' => 25,
                    'name' => '文章栏目删除',
                    'pid' => 20,
                    'action' => 'admin_category_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            25 =>
                array (
                    'id' => 26,
                    'name' => 'Tag标签管理',
                    'pid' => 5,
                    'action' => 'admin_tag',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            26 =>
                array (
                    'id' => 27,
                    'name' => 'Tag标签添加',
                    'pid' => 26,
                    'action' => 'admin_tag_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            27 =>
                array (
                    'id' => 28,
                    'name' => 'Tag标签添加提交',
                    'pid' => 27,
                    'action' => 'admin_tag_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            28 =>
                array (
                    'id' => 29,
                    'name' => 'Tag标签修改',
                    'pid' => 26,
                    'action' => 'admin_tag_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            29 =>
                array (
                    'id' => 30,
                    'name' => 'Tag标签修改提交',
                    'pid' => 29,
                    'action' => 'admin_tag_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            30 =>
                array (
                    'id' => 31,
                    'name' => 'Tag标签删除',
                    'pid' => 26,
                    'action' => 'admin_tag_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            31 =>
                array (
                    'id' => 32,
                    'name' => '单页管理',
                    'pid' => 1,
                    'action' => 'admin_page',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            32 =>
                array (
                    'id' => 33,
                    'name' => '单页添加',
                    'pid' => 32,
                    'action' => 'admin_page_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            33 =>
                array (
                    'id' => 34,
                    'name' => '单页添加提交',
                    'pid' => 33,
                    'action' => 'admin_page_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            34 =>
                array (
                    'id' => 35,
                    'name' => '单页修改',
                    'pid' => 32,
                    'action' => 'admin_page_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            35 =>
                array (
                    'id' => 36,
                    'name' => '单页修改提交',
                    'pid' => 35,
                    'action' => 'admin_page_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            36 =>
                array (
                    'id' => 37,
                    'name' => '单页删除',
                    'pid' => 32,
                    'action' => 'admin_page_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            37 =>
                array (
                    'id' => 38,
                    'name' => '商品列表',
                    'pid' => 2,
                    'action' => 'admin_goods',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            38 =>
                array (
                    'id' => 39,
                    'name' => '商品添加',
                    'pid' => 2,
                    'action' => 'admin_goods_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            39 =>
                array (
                    'id' => 40,
                    'name' => '商品添加提交',
                    'pid' => 39,
                    'action' => 'admin_goods_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            40 =>
                array (
                    'id' => 41,
                    'name' => '商品修改',
                    'pid' => 2,
                    'action' => 'admin_goods_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            41 =>
                array (
                    'id' => 42,
                    'name' => '商品修改提交',
                    'pid' => 41,
                    'action' => 'admin_goods_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            42 =>
                array (
                    'id' => 43,
                    'name' => '商品删除',
                    'pid' => 2,
                    'action' => 'admin_goods_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            43 =>
                array (
                    'id' => 44,
                    'name' => '重复商品',
                    'pid' => 2,
                    'action' => 'admin_goods_recommendarc',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            44 =>
                array (
                    'id' => 45,
                    'name' => '商品是否存在',
                    'pid' => 2,
                    'action' => 'admin_goods_goodsexists',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            45 =>
                array (
                    'id' => 46,
                    'name' => '商品分类',
                    'pid' => 2,
                    'action' => 'admin_goodstype',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            46 =>
                array (
                    'id' => 47,
                    'name' => '商品分类添加',
                    'pid' => 46,
                    'action' => 'admin_goodstype_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            47 =>
                array (
                    'id' => 48,
                    'name' => '商品分类添加提交',
                    'pid' => 47,
                    'action' => 'admin_goodstype_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            48 =>
                array (
                    'id' => 49,
                    'name' => '商品分类修改',
                    'pid' => 46,
                    'action' => 'admin_producttype_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            49 =>
                array (
                    'id' => 50,
                    'name' => '商品分类修改提交',
                    'pid' => 42,
                    'action' => 'admin_producttype_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            50 =>
                array (
                    'id' => 51,
                    'name' => '商品分类删除',
                    'pid' => 46,
                    'action' => 'admin_goodstype_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            51 =>
                array (
                    'id' => 52,
                    'name' => '友情链接',
                    'pid' => 5,
                    'action' => 'admin_friendlink',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            52 =>
                array (
                    'id' => 53,
                    'name' => '友情链接添加',
                    'pid' => 52,
                    'action' => 'admin_friendlink_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            53 =>
                array (
                    'id' => 54,
                    'name' => '友情链接添加提交',
                    'pid' => 53,
                    'action' => 'admin_friendlink_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            54 =>
                array (
                    'id' => 55,
                    'name' => '友情链接修改',
                    'pid' => 52,
                    'action' => 'admin_friendlink_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            55 =>
                array (
                    'id' => 56,
                    'name' => '友情链接修改提交',
                    'pid' => 55,
                    'action' => 'admin_friendlink_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            56 =>
                array (
                    'id' => 57,
                    'name' => '友情链接删除',
                    'pid' => 52,
                    'action' => 'admin_friendlink_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            57 =>
                array (
                    'id' => 58,
                    'name' => '关键词管理',
                    'pid' => 5,
                    'action' => 'admin_keyword',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            58 =>
                array (
                    'id' => 59,
                    'name' => '关键词添加',
                    'pid' => 58,
                    'action' => 'admin_keyword_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            59 =>
                array (
                    'id' => 60,
                    'name' => '关键词添加提交',
                    'pid' => 59,
                    'action' => 'admin_keyword_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            60 =>
                array (
                    'id' => 61,
                    'name' => '关键词修改',
                    'pid' => 58,
                    'action' => 'admin_keyword_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            61 =>
                array (
                    'id' => 62,
                    'name' => '关键词修改提交',
                    'pid' => 61,
                    'action' => 'admin_keyword_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            62 =>
                array (
                    'id' => 63,
                    'name' => '关键词删除',
                    'pid' => 58,
                    'action' => 'admin_keyword_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            63 =>
                array (
                    'id' => 64,
                    'name' => '搜索关键词',
                    'pid' => 5,
                    'action' => 'admin_searchword',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            64 =>
                array (
                    'id' => 65,
                    'name' => '搜索关键词添加',
                    'pid' => 64,
                    'action' => 'admin_searchword_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            65 =>
                array (
                    'id' => 66,
                    'name' => '搜索关键词添加提交',
                    'pid' => 65,
                    'action' => 'admin_searchword_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            66 =>
                array (
                    'id' => 67,
                    'name' => '搜索关键词修改',
                    'pid' => 64,
                    'action' => 'admin_searchword_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            67 =>
                array (
                    'id' => 68,
                    'name' => '搜索关键词修改提交',
                    'pid' => 67,
                    'action' => 'admin_searchword_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            68 =>
                array (
                    'id' => 69,
                    'name' => '搜索关键词删除',
                    'pid' => 64,
                    'action' => 'admin_searchword_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            69 =>
                array (
                    'id' => 70,
                    'name' => '轮播图',
                    'pid' => 5,
                    'action' => 'admin_slide',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            70 =>
                array (
                    'id' => 71,
                    'name' => '轮播图添加',
                    'pid' => 70,
                    'action' => 'admin_slide_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            71 =>
                array (
                    'id' => 72,
                    'name' => '轮播图添加提交',
                    'pid' => 71,
                    'action' => 'admin_slide_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            72 =>
                array (
                    'id' => 73,
                    'name' => '轮播图修改',
                    'pid' => 70,
                    'action' => 'admin_slide_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            73 =>
                array (
                    'id' => 74,
                    'name' => '轮播图修改提交',
                    'pid' => 73,
                    'action' => 'admin_slide_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            74 =>
                array (
                    'id' => 75,
                    'name' => '轮播图删除',
                    'pid' => 70,
                    'action' => 'admin_slide_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            75 =>
                array (
                    'id' => 76,
                    'name' => '在线留言',
                    'pid' => 5,
                    'action' => 'admin_guestbook',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            76 =>
                array (
                    'id' => 77,
                    'name' => '在线留言删除',
                    'pid' => 76,
                    'action' => 'admin_guestbook_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            77 =>
                array (
                    'id' => 78,
                    'name' => '系统基本参数',
                    'pid' => 6,
                    'action' => 'admin_sysconfig',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            78 =>
                array (
                    'id' => 79,
                    'name' => '系统参数添加',
                    'pid' => 78,
                    'action' => 'admin_sysconfig_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            79 =>
                array (
                    'id' => 80,
                    'name' => '系统参数添加提交',
                    'pid' => 79,
                    'action' => 'admin_sysconfig_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            80 =>
                array (
                    'id' => 81,
                    'name' => '系统参数修改',
                    'pid' => 78,
                    'action' => 'admin_sysconfig_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            81 =>
                array (
                    'id' => 82,
                    'name' => '系统参数修改提交',
                    'pid' => 81,
                    'action' => 'admin_sysconfig_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            82 =>
                array (
                    'id' => 83,
                    'name' => '系统参数删除',
                    'pid' => 78,
                    'action' => 'admin_sysconfig_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            83 =>
                array (
                    'id' => 84,
                    'name' => '管理员',
                    'pid' => 4,
                    'action' => 'admin_admin',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            84 =>
                array (
                    'id' => 85,
                    'name' => '管理员添加',
                    'pid' => 84,
                    'action' => 'admin_admin_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            85 =>
                array (
                    'id' => 86,
                    'name' => '管理员添加提交',
                    'pid' => 85,
                    'action' => 'admin_admin_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            86 =>
                array (
                    'id' => 87,
                    'name' => '管理员修改',
                    'pid' => 84,
                    'action' => 'admin_admin_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            87 =>
                array (
                    'id' => 88,
                    'name' => '管理员修改提交',
                    'pid' => 87,
                    'action' => 'admin_admin_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            88 =>
                array (
                    'id' => 89,
                    'name' => '管理员删除',
                    'pid' => 84,
                    'action' => 'admin_admin_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            89 =>
                array (
                    'id' => 90,
                    'name' => '角色管理',
                    'pid' => 4,
                    'action' => 'admin_adminrole',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            90 =>
                array (
                    'id' => 91,
                    'name' => '角色添加',
                    'pid' => 90,
                    'action' => 'admin_adminrole_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            91 =>
                array (
                    'id' => 92,
                    'name' => '角色添加修改',
                    'pid' => 91,
                    'action' => 'admin_adminrole_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            92 =>
                array (
                    'id' => 93,
                    'name' => '角色修改',
                    'pid' => 90,
                    'action' => 'admin_adminrole_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            93 =>
                array (
                    'id' => 94,
                    'name' => '角色修改提交',
                    'pid' => 93,
                    'action' => 'admin_adminrole_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            94 =>
                array (
                    'id' => 95,
                    'name' => '角色删除',
                    'pid' => 90,
                    'action' => 'admin_adminrole_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            95 =>
                array (
                    'id' => 96,
                    'name' => '后台菜单',
                    'pid' => 3,
                    'action' => 'admin_menu',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            96 =>
                array (
                    'id' => 97,
                    'name' => '菜单添加',
                    'pid' => 96,
                    'action' => 'admin_menu_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            97 =>
                array (
                    'id' => 98,
                    'name' => '菜单添加提交',
                    'pid' => 97,
                    'action' => 'admin_menu_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            98 =>
                array (
                    'id' => 99,
                    'name' => '菜单修改',
                    'pid' => 96,
                    'action' => 'admin_menu_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            99 =>
                array (
                    'id' => 100,
                    'name' => '菜单修改提交',
                    'pid' => 99,
                    'action' => 'admin_menu_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            100 =>
                array (
                    'id' => 101,
                    'name' => '菜单删除',
                    'pid' => 96,
                    'action' => 'admin_menu_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            101 =>
                array (
                    'id' => 102,
                    'name' => '权限设置',
                    'pid' => 90,
                    'action' => 'admin_adminrole_permissions',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            102 =>
                array (
                    'id' => 103,
                    'name' => '权限设置提交',
                    'pid' => 102,
                    'action' => 'admin_adminrole_dopermissions',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            103 =>
                array (
                    'id' => 104,
                    'name' => '欢迎页面',
                    'pid' => 5,
                    'action' => 'admin_welcome',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 5,
                ),
            104 =>
                array (
                    'id' => 105,
                    'name' => '微信开发管理',
                    'pid' => 0,
                    'action' => 'weixin_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-th-large',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            105 =>
                array (
                    'id' => 106,
                    'name' => '微信自定义菜单',
                    'pid' => 105,
                    'action' => 'admin_weixinmenu',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            106 =>
                array (
                    'id' => 107,
                    'name' => '商品品牌',
                    'pid' => 2,
                    'action' => 'admin_goodsbrand',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            107 =>
                array (
                    'id' => 108,
                    'name' => '品牌添加',
                    'pid' => 107,
                    'action' => 'admin_goodsbrand_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            108 =>
                array (
                    'id' => 109,
                    'name' => '品牌添加提交',
                    'pid' => 108,
                    'action' => 'admin_goodsbrand_doadd',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            109 =>
                array (
                    'id' => 110,
                    'name' => '品牌修改',
                    'pid' => 107,
                    'action' => 'admin_goodsbrand_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            110 =>
                array (
                    'id' => 111,
                    'name' => '品牌修改提交',
                    'pid' => 110,
                    'action' => 'admin_goodsbrand_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            111 =>
                array (
                    'id' => 112,
                    'name' => '品牌删除',
                    'pid' => 107,
                    'action' => 'admin_goodsbrand_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            112 =>
                array (
                    'id' => 113,
                    'name' => '订单管理',
                    'pid' => 0,
                    'action' => 'order_default',
                    'data' => '',
                    'type' => 0,
                    'icon' => 'glyphicon glyphicon-credit-card',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            113 =>
                array (
                    'id' => 114,
                    'name' => '订单列表',
                    'pid' => 113,
                    'action' => 'admin_order',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            114 =>
                array (
                    'id' => 115,
                    'name' => '订单详情',
                    'pid' => 113,
                    'action' => 'admin_order_detail',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            115 =>
                array (
                    'id' => 116,
                    'name' => '订单修改',
                    'pid' => 113,
                    'action' => 'admin_order_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            116 =>
                array (
                    'id' => 117,
                    'name' => '订单修改提交',
                    'pid' => 116,
                    'action' => 'admin_order_doedit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            117 =>
                array (
                    'id' => 118,
                    'name' => '会员管理',
                    'pid' => 4,
                    'action' => 'admin_user',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            118 =>
                array (
                    'id' => 119,
                    'name' => '提现申请',
                    'pid' => 4,
                    'action' => 'admin_userwithdraw',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            119 =>
                array (
                    'id' => 120,
                    'name' => '意见反馈',
                    'pid' => 5,
                    'action' => 'admin_feedback',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            120 =>
                array (
                    'id' => 121,
                    'name' => '意见反馈删除',
                    'pid' => 120,
                    'action' => 'admin_feedback_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            121 =>
                array (
                    'id' => 122,
                    'name' => '快递管理',
                    'pid' => 113,
                    'action' => 'admin_kuaidi',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            122 =>
                array (
                    'id' => 123,
                    'name' => '快递添加',
                    'pid' => 122,
                    'action' => 'admin_kuaidi_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            123 =>
                array (
                    'id' => 124,
                    'name' => '快递修改',
                    'pid' => 122,
                    'action' => 'admin_kuaidi_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            124 =>
                array (
                    'id' => 125,
                    'name' => '快递删除',
                    'pid' => 122,
                    'action' => 'admin_kuaidi_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            125 =>
                array (
                    'id' => 126,
                    'name' => '优惠券管理',
                    'pid' => 2,
                    'action' => 'admin_bonus',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 1,
                    'listorder' => 50,
                ),
            126 =>
                array (
                    'id' => 127,
                    'name' => '优惠券添加',
                    'pid' => 126,
                    'action' => 'admin_bonus_add',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            127 =>
                array (
                    'id' => 128,
                    'name' => '优惠券啊修改',
                    'pid' => 126,
                    'action' => 'admin_bonus_edit',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
            128 =>
                array (
                    'id' => 129,
                    'name' => '优惠券删除',
                    'pid' => 126,
                    'action' => 'admin_bonus_del',
                    'data' => '',
                    'type' => 1,
                    'icon' => '',
                    'des' => '',
                    'status' => 0,
                    'listorder' => 50,
                ),
        );
        foreach($menu as $value){
            Menu::create($value);
        }
        //


    }
}
